<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>

</body>
<script type="text/javascript">






	
// Example: Synchronous vs Asynchronous
console.log('Start');
 
// The timeout is set, but the below code continues to execute without waiting for the timeout to complete.
setTimeout(() => {
	console.log('Async Task');
}, 1000);
 
console.log('End');
 
// Result
// ----------
// Logs: Start, End, Async Task








// Example: Promises
const promise = new Promise((resolve, reject) => {
	setTimeout(() => {
		resolve('Promise Resolved');
	}, 1000);
}).then((result) => {
	// In this case result will contain 'Promise Resolved' since that string was passed to the resolve function.
	// This chained function will only execute after the promise has been resolved, so in this case after 1 second.
	console.log(result);
});










// In this example, the user will win the coin flip if the result is 'Heads'.
 
const coinFlip = (message) => {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			const isHeads = Math.random() > 0.5;
			if (isHeads) {
				resolve(`${message}: Heads! You Win!`);
			} else {
				reject(`${message}: Tails! You Lose!`);
			}
		}, 1000);
	});
};
 
coinFlip('First flip')
	.then(result => {
		console.log(result); // Output: First flip: Heads
		return coinFlip('Second flip', 1000);
	})
	.then(result => {
		console.log(result); // Output: Second flip: Heads
		return coinFlip('Third flip', 1000);
	})
	.then(result => {
		console.log(result); // Output: Third flip: Heads
	})
	.catch(error => {
		console.error('Coin flip lost!', error);
	});










async function fetchUserData(userId) {
 
	// Fetch user data
	// In these examples each function is presumed to a asynchronous function.
	
	// Fetch the user data from the database
	//     Get the used data after the user data has been fetched from the database.
	const userData = await fetchUserFromDatabase(userId);
	
	// Fetch additional user info after the user data has been fetched above
	const additionalInfo = await fetchAdditionalUserInfo(userData.id);
	
	// Process and return user data
	//   This synchronous function will only run after the previous two asynchronous functions have been resolved.
	const processedData = processData(userData, additionalInfo);
 
	return processedData;
}
 
// Usage
fetchUserData(123)
	.then(processedUserData => {
		console.log(processedUserData);
	})
	.catch(error => console.error('Error:', error));













const fetchRequest = () => {
	// A new request is made to the URL provided
	fetch('https://icanhazdadjoke.com/', {
		headers: {
			'Accept': 'application/json'
		}
	})
	// The response is then validated and converted to a JSON object
	.then(response => {
		if (!response.ok) {
			// This will force the catch block to run
			throw new Error('Network response was not ok');
		}
		return response.json();
	})
	// The JS object is then passed to the next step to be worked with
	.then(data => {
		console.log('Fetch API:', data.joke);
	})
	// Only ever runs if an error is thrown above
	.catch(error => {
		console.error('Fetch error:', error);
	});
	
};
 
fetchRequest();













</script>
</html>